# gen_font.ps1 - generate 16px bitmap fonts for the OLED project (font_data.h)
# Chinese glyphs (Unicode codepoints): U+84DD U+7259 U+63A5 U+6536 U+53D1
#                                      U+9001 U+6D3B U+52A8 U+6700 U+8FD1
# ASCII glyphs: 0x20..0x7E as 8x16 cells
# Output: font_data.h next to this script (UTF-8 without BOM, ASCII-only content)

Add-Type -AssemblyName System.Drawing

$script:CV = 32
$script:THR = 100

function Draw-Glyph {
    param([string]$ch, [single]$size, [int]$drawY)
    $bmp = New-Object System.Drawing.Bitmap($script:CV, $script:CV)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear([System.Drawing.Color]::Black)
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
    $font = New-Object System.Drawing.Font('SimHei', $size, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
    $fmt = [System.Drawing.StringFormat]::GenericTypographic
    $sz = $g.MeasureString($ch, $font, 1000, $fmt)
    $x = [single](($script:CV - $sz.Width) / 2)
    $g.DrawString($ch, $font, [System.Drawing.Brushes]::White, $x, [single]$drawY, $fmt)
    $g.Dispose()
    return $bmp
}

function Get-BBox {
    param($bmp)
    $minX = $script:CV; $maxX = -1; $minY = $script:CV; $maxY = -1
    for ($y = 0; $y -lt $script:CV; $y++) {
        for ($x = 0; $x -lt $script:CV; $x++) {
            if ($bmp.GetPixel($x, $y).R -gt $script:THR) {
                if ($x -lt $minX) { $minX = $x }
                if ($x -gt $maxX) { $maxX = $x }
                if ($y -lt $minY) { $minY = $y }
                if ($y -gt $maxY) { $maxY = $y }
            }
        }
    }
    return @{ minX=$minX; maxX=$maxX; minY=$minY; maxY=$maxY }
}

function Extract-Bits {
    param($bmp, [int]$ox, [int]$oy, [int]$w, [int]$h)
    $rows = @()
    for ($r = 0; $r -lt $h; $r++) {
        $rowBytes = @()
        for ($c = 0; $c -lt ($w / 8); $c++) {
            $b = 0
            for ($k = 0; $k -lt 8; $k++) {
                $xx = $ox + $c * 8 + $k
                $yy = $oy + $r
                if ($xx -ge 0 -and $xx -lt $script:CV -and $yy -ge 0 -and $yy -lt $script:CV) {
                    if ($bmp.GetPixel($xx, $yy).R -gt $script:THR) { $b = $b -bor (1 -shl (7 - $k)) }
                }
            }
            $rowBytes += $b
        }
        $rows += ,$rowBytes
    }
    return ,$rows
}

function Dump-Art {
    param($rows)
    foreach ($rb in $rows) {
        $line = ''
        foreach ($b in $rb) {
            for ($k = 7; $k -ge 0; $k--) { if ($b -band (1 -shl $k)) { $line += '#' } else { $line += '.' } }
        }
        Write-Output $line
    }
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$cnCodes = @(0x84DD, 0x7259, 0x63A5, 0x6536, 0x53D1, 0x9001, 0x6D3B, 0x52A8, 0x6700, 0x8FD1)
$asciiCodes = 0x20..0x7E

# --- 基准：统一基线/居中偏移 ---
$refH = Draw-Glyph -ch 'H' -size 12 -drawY 9
$bbH = Get-BBox $refH
$refH.Dispose()
$ascCropY = $bbH.minY - 3          # 大写字母顶部落在第 3 行（下方留出与下一行的间隙）

$refCn = Draw-Glyph -ch ([string][char]0x84DD) -size 13 -drawY 7
$bbCn = Get-BBox $refCn
$cnH = $bbCn.maxY - $bbCn.minY + 1
$cnCropY = $bbCn.minY - [math]::Floor((16 - $cnH) / 2)
$refCn.Dispose()

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine('/* font_data.h - generated by gen_font.ps1 (SimHei), do not edit manually */')
[void]$out.AppendLine('/* Chinese glyph order: U+84DD U+7259 U+63A5 U+6536 U+53D1 U+9001 U+6D3B U+52A8 U+6700 U+8FD1 */')
[void]$out.AppendLine('')

[void]$out.AppendLine('/* 16x16 Chinese glyphs, row-major, 2 bytes per row (left 8 bits first) */')
[void]$out.AppendLine('static const uint8_t font_cn16[10][32] = {')
foreach ($code in $cnCodes) {
    $bmp = Draw-Glyph -ch ([string][char]$code) -size 13 -drawY 7
    $bb = Get-BBox $bmp
    $w = $bb.maxX - $bb.minX + 1
    $cropX = $bb.minX - [math]::Floor((16 - $w) / 2)
    $rows = Extract-Bits -bmp $bmp -ox $cropX -oy $cnCropY -w 16 -h 16
    $bmp.Dispose()
    $vals = @()
    foreach ($rb in $rows) { $vals += ('0x{0:X2},0x{1:X2}' -f $rb[0], $rb[1]) }
    [void]$out.AppendLine('    { ' + ($vals -join ', ') + ' }, /* U+' + ('{0:X4}' -f $code) + ' */')
}
[void]$out.AppendLine('};')
[void]$out.AppendLine('')

[void]$out.AppendLine('/* UTF-8 bytes of the glyphs above (matches UTF-8 source literals) */')
[void]$out.AppendLine('static const char cn_utf8[10][3] = {')
foreach ($code in $cnCodes) {
    $ub = [System.Text.Encoding]::UTF8.GetBytes([string][char]$code)
    $s = '    { (char)0x' + ('{0:X2}' -f $ub[0]) + ', (char)0x' + ('{0:X2}' -f $ub[1]) + ', (char)0x' + ('{0:X2}' -f $ub[2]) + ' }, /* U+' + ('{0:X4}' -f $code) + ' */'
    [void]$out.AppendLine($s)
}
[void]$out.AppendLine('};')
[void]$out.AppendLine('')

[void]$out.AppendLine('/* 8x16 ASCII glyphs 0x20..0x7E, row-major, 1 byte per row (MSB = leftmost) */')
[void]$out.AppendLine('static const uint8_t font_ascii16[95][16] = {')
foreach ($code in $asciiCodes) {
    $bmp = Draw-Glyph -ch ([string][char]$code) -size 12 -drawY 9
    $bb = Get-BBox $bmp
    if ($bb.maxX -lt 0) {
        # 无墨迹（如空格）：全 0
        $rows = @()
        for ($r = 0; $r -lt 16; $r++) { $rows += ,@(0) }
    } else {
        $w = $bb.maxX - $bb.minX + 1
        $cropX = $bb.minX - [math]::Floor((8 - $w) / 2)
        $rows = Extract-Bits -bmp $bmp -ox $cropX -oy $ascCropY -w 8 -h 16
    }
    $bmp.Dispose()
    $vals = @()
    foreach ($rb in $rows) { $vals += ('0x{0:X2}' -f $rb[0]) }
    [void]$out.AppendLine('    { ' + ($vals -join ',') + ' },')
}
[void]$out.AppendLine('};')

$outPath = Join-Path $scriptDir 'font_data.h'
[System.IO.File]::WriteAllText($outPath, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output ('written: ' + $outPath)

Write-Output '--- preview U+84DD (16x16) ---'
$p = Draw-Glyph -ch ([string][char]0x84DD) -size 13 -drawY 7; $b = Get-BBox $p
Dump-Art (Extract-Bits -bmp $p -ox ($b.minX - [math]::Floor((16 - ($b.maxX-$b.minX+1))/2)) -oy $cnCropY -w 16 -h 16); $p.Dispose()
Write-Output '--- preview U+6700 (16x16) ---'
$p = Draw-Glyph -ch ([string][char]0x6700) -size 13 -drawY 7; $b = Get-BBox $p
Dump-Art (Extract-Bits -bmp $p -ox ($b.minX - [math]::Floor((16 - ($b.maxX-$b.minX+1))/2)) -oy $cnCropY -w 16 -h 16); $p.Dispose()
Write-Output "--- preview 'h' (8x16) ---"
$p = Draw-Glyph -ch 'h' -size 12 -drawY 9; $b = Get-BBox $p
Dump-Art (Extract-Bits -bmp $p -ox ($b.minX - [math]::Floor((8 - ($b.maxX-$b.minX+1))/2)) -oy $ascCropY -w 8 -h 16); $p.Dispose()
Write-Output "--- preview '9' (8x16) ---"
$p = Draw-Glyph -ch '9' -size 12 -drawY 9; $b = Get-BBox $p
Dump-Art (Extract-Bits -bmp $p -ox ($b.minX - [math]::Floor((8 - ($b.maxX-$b.minX+1))/2)) -oy $ascCropY -w 8 -h 16); $p.Dispose()